In [13]:
import torch

In [2]:
a = torch.randn(5,5)

In [3]:
a

tensor([[-2.0772, -1.3956,  0.2912,  1.0987,  0.7305],
        [-0.9522,  0.2342,  0.6568,  0.8923,  0.1526],
        [ 0.8685, -0.4909, -0.5898, -0.5882,  1.3270],
        [-0.2687,  0.3178,  0.7840,  0.5891,  0.8950],
        [-0.6044, -2.3919,  0.0205,  1.0128, -0.4868]])

In [4]:
b = torch.randn(5,5)
b

tensor([[-7.6399e-01, -9.5051e-01,  1.1096e+00, -9.9566e-02, -1.6064e+00],
        [ 1.0896e-03, -7.0136e-01, -6.9219e-01, -2.4993e-01,  1.6817e+00],
        [ 1.5410e+00, -2.4137e-01, -8.6688e-01,  1.2084e+00,  1.5351e+00],
        [-1.5412e+00,  4.5528e-01,  9.6485e-01, -1.3109e-01,  1.4079e+00],
        [-7.5936e-01, -7.6928e-01,  1.2922e+00, -2.0333e+00, -1.8207e-02]])

In [5]:
a@b

tensor([[-0.2139,  2.8212,  0.4128, -0.7219,  2.9706],
        [ 0.2486,  0.8711, -0.7298,  0.4025,  4.1852],
        [-1.6740, -1.6274,  2.9619, -3.2974, -3.9784],
        [-0.1739, -0.5770,  0.5273, -1.0024,  2.9826],
        [-0.7004,  3.0827,  1.3154,  1.5398, -1.5852]])

In [16]:
c = torch.tensor([[1, -1, 2],
                  [-13, 9, -16],
                  [9, -7, 12]])
c

tensor([[  1,  -1,   2],
        [-13,   9, -16],
        [  9,  -7,  12]])

In [19]:
d = torch.tensor([[3],
                  [5],
                  [1]])
d

tensor([[3],
        [5],
        [1]])

In [20]:
c@d

tensor([[  0],
        [-10],
        [  4]])